name: docker-buildx
on:
  pull_request:
    branches:
      - master
      - experimental
  push:
    branches:
      - '**'
    tags:
      - '*.*'

jobs:
  create-release:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 18
      -
        name: Install Deps
        run: npm install --unsafe-perm
      -
        name: Create Release
        run: npm run create-release -- --skip-opt-packages=ffmpeg-static,ffprobe-static --force-opt-packages
      - uses: actions/upload-artifact@v4
        with:
          name: pigallery2-release
          path: release
  build-dockerx:
    runs-on: [ ubuntu-latest ]
    needs: [ create-release ]
    strategy:
      matrix:
        container: [alpine]
        include:
          - container: alpine
            platforms: linux/arm/v6,linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pigallery2-release
          path: pigallery2-release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.container }}/Dockerfile.build
          platforms: ${{ matrix.platforms }}
      - name: Push experimental
        if: ${{ github.ref == 'refs/heads/experimental' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.container }}/Dockerfile.build
          platforms: ${{ matrix.platforms }}
          push: true
          tags: bpatrik/pigallery2:experimental-${{ matrix.container }}
      - name: Push edge on new master commit
        # github.ref:  branches the format is refs/heads/<branch_name>  PRs and Tags are different
        if: ${{github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.container }}/Dockerfile.build
          platforms: ${{ matrix.platforms }}
          push: true
          tags: bpatrik/pigallery2:edge-${{ matrix.container }}
      - name: Push release on new Tag
        if: ${{ startsWith(github.ref_type , 'tag') &&  !github.event.issue.pull_request &&  matrix.container != 'debian-bookworm'}}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.container }}/Dockerfile.build
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            bpatrik/pigallery2:edge-${{ matrix.container }}
            bpatrik/pigallery2:${{ github.ref_name }}-${{ matrix.container }}
            bpatrik/pigallery2:latest-${{ matrix.container }}
      - name: Push latest on new Tag
        if: ${{ startsWith(github.ref_type, 'tag') &&  !github.event.issue.pull_request &&  matrix.container == 'debian-bookworm'}}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.container }}/Dockerfile.build
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            bpatrik/pigallery2:edge-${{ matrix.container }}
            bpatrik/pigallery2:${{ github.ref_name }}-${{ matrix.container }}
            bpatrik/pigallery2:latest-${{ matrix.container }}
            bpatrik/pigallery2:${{ github.ref_name }}
            bpatrik/pigallery2:latest
